TBCA\ApiBundle\Entity\AlimentoNutriente:
    type: entity
    table: alimento_nutriente
    indexes:
        fk_id_nutriente:
            columns:
                - id_nutriente
    id:
        idAlimento:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_alimento
        idNutriente:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_nutriente
    fields:
        valor:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
