TBCA\ApiBundle\Entity\Alimento:
    type: entity
    repositoryClass: TBCA\ApiBundle\Entity\AlimentoRepository
    table: alimento
    indexes:
        fk_id_categoria:
            columns:
                - id_categoria
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        idCategoria:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_categoria
    lifecycleCallbacks: {  }
