TBCA\ApiBundle\Entity\Nutriente:
    type: entity
    repositoryClass: TBCA\ApiBundle\Entity\NutrienteRepository
    table: nutriente
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        unidade:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
